---


- name: Beat input configuration
  template:
    src: "inputs/01-beats-input.conf.j2"
    dest: "{{ logstash_config_dir }}/conf.d/01-beats-input.conf"
    owner: root
    group: root
    mode: 0644
  when: logstash_beat_input_enable
  notify: restart logstash

- name: Beat input configuration absent if disabled.
  file:
    path: "{{ logstash_config_dir }}/conf.d/01-beats-input.conf"
    state: absent
  when: not logstash_beat_input_enable
  notify: restart logstash

- name: Local syslog configuration
  template:
    src: "inputs/02-local-syslog-input.conf.j2"
    dest: "{{ logstash_config_dir }}/conf.d/02-local-syslog-input.conf"
    owner: root
    group: root
    mode: 0644
  when: logstash_local_syslog_input_enable
  notify: restart logstash

- name: Local syslog configuration absent if disabled.
  file:
    path: "{{ logstash_config_dir }}/conf.d/02-local-syslog-input.conf"
    state: absent
  when: not logstash_local_syslog_input_enable
  notify: restart logstash

- name: Redis input configuration
  template:
    src: "inputs/03-redis-input.conf.j2"
    dest: "{{ logstash_config_dir }}/conf.d/03-redis-input.conf"
    owner: root
    group: root
    mode: 0644
  when: logstash_redis_input_enable
  notify: restart logstash

- name: Redis input configuration absent if disabled.
  file:
    path: "{{ logstash_config_dir }}/conf.d/03-redis-input.conf"
    state: absent
  when: not logstash_redis_input_enable
  notify: restart logstash


- name: Elasticsearch output configuration
  template:
    src: "outputs/30-elasticsearch-output.conf.j2"
    dest: "{{ logstash_config_dir }}/conf.d/30-elasticsearch-output.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash


- name: Create Logstash filters.
  template:
    src: "{{ item }}"
    dest: "{{ logstash_config_dir }}/conf.d/{{ item|basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - templates/filters/*.conf
  notify: restart logstash




