---

- name: Include optional user and group creation.
  include: logstash-optional-user.yml
  become: yes
  become_user: root

- name: "Create Logstash Data dir "
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: "0755"
  with_items:
    - "{{ logstash_logs_dir }}"
    - "{{ logstash_data_dir }}"
  become: yes
  
- name: "Create Logstash config dir "
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0755"
  with_items:
    - "{{ logstash_config_dir }}"
    - "{{ logstash_config_dir }}/conf.d"
  become: yes


- name: "Copy tar gz"
  become: yes
  copy:
    src: "{{ logstash_download_path }}/{{ logstash_tarball }}.tar.gz"
    dest: "/tmp/{{ logstash_tarball }}.tar.gz"

- name: Extract the Logstash tarball
  become: yes
  unarchive:
    src: "/tmp/{{ logstash_tarball }}.tar.gz"
    dest: "/tmp/"
    copy: no
    creates: "/tmp/{{ logstash_tarball }}"

- name: Install Logstash
  become: yes
  command: "cp -R /tmp/{{ logstash_tarball }} {{ logstash_install_dir }}"
  args:
    creates: "{{ logstash_install_dir }}"
    removes: "/tmp/{{ logstash_tarball }}"




- name    : get files in config
  shell   : ls -1 "{{ logstash_install_dir }}/config/"
  register: config_files

- name: Copy configration
  copy:
    remote_src: True
    src : "{{ logstash_install_dir }}/config/{{item}}"
    dest: "{{ logstash_config_dir }}/"
  with_items: "{{ config_files.stdout_lines }}"
  become: yes

- name: Remove old files foo
  file: path={{ logstash_install_dir }}/config state=absent
  become: yes

- name: Replace logstash configration
  become: yes
  template:
    src: logstash.yml.j2
    dest: "{{ logstash_config_dir }}/logstash.yml"
    mode: 0644
  notify:
    - restart logstash


- name: Ensure Systemd Service Configuraiton
  become: yes
  template:
    src: logstash.service.j2
    dest: /etc/systemd/system/logstash.service
    mode: 0744
  notify:
    - restart logstash
  when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: Install Logstash service
  become: yes
  template:
    src: service.conf.j2
    dest: /etc/init/logstash.conf
    mode: 0744
  notify:
    - restart logstash
  when: ansible_service_mgr is not defined or ansible_service_mgr != 'systemd'

- name: Enable Logstash service
  become: yes
  service:
    name: logstash
    enabled: yes
  notify:
    - restart logstash

- name: Remove tmp files
  become: yes
  file:
    path: "/tmp/{{ logstash_tarball }}"
    state: absent
