---
#Add the logstash user before installing from packages.
- name: Ensure optional logstash group is created with the correct id.
  group:
    state: present
    name: "{{ logstash_group }}"
    system: yes

- name: Ensure optional logstash user is created with the correct id.
  user:
    state: present
    name: "{{ logstash_user }}"
    comment: logstash system user
    system: yes
    createhome: no
    group: "{{ logstash_group }}"
  
