---

- include: set-role-variables.yml

- include: install.yml

- include: config.yml
- include: ssl.yml


- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"


- include: plugins.yml
