---
# - name: Add Elasticsearch GPG key.
#   rpm_key:
#     key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
#     state: present

# - name: Add Logstash repository.
#   copy:
#     src: logstash.repo
#     dest: /etc/yum.repos.d/logstash.repo
#     mode: 0644

- name: "Copy Logstash RPM"
  copy: src="../files/elk/logstash-5.1.2.rpm" dest="/tmp/logstash-5.1.2.rpm"

- name: Install Logstash
  yum: pkg=/tmp/logstash-5.1.2.rpm state=installed
